# Generated by Django 4.2.2 on 2023-06-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="icon",
        ),
    ]
